'use client'
import './globals.css'
import {Inter} from 'next/font/google'
import Header from "@/component/landing_page/header";
import {Provider} from "react-redux";
import {store} from './store/store'

const inter = Inter({subsets: ['latin']})


export const metadata = {
    title: 'e-commerce site demo',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <Provider store={store}>
            <body className={`${inter.className} container mx-auto px-6 py-3`}>
            <Header/>
            {children}
            </body>
        </Provider>
        </html>
    )
}

